include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact-name: totem-dongle-left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem-dongle-right
  - board: seeeduino_xiao_ble
    shield: totem_dongle prospector_adapter
    snippet: zmk-usb-logging
    artifact-name: totem-dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: totem-settings-reset
