include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    #snippet: zmk-usb-logging
    #snippet: studio-rpc-usb-uart
    artifact-name: dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
